/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Comments: () => import('#controllers/comments_controller'),
  Events: () => import('#controllers/events_controller'),
  Exams: () => import('#controllers/exams_controller'),
  Notes: () => import('#controllers/notes_controller'),
  QuestionReports: () => import('#controllers/question_reports_controller'),
  Questions: () => import('#controllers/questions_controller'),
  Subjects: () => import('#controllers/subjects_controller'),
  Uploads: () => import('#controllers/uploads_controller'),
  Users: () => import('#controllers/users_controller'),
}
